### ISSUE TITLE
Potential bug: transformation has no effect in parse_ply?

### ISSUE THREAD

**Issue by arthur-x** [BachiLi/lajolla_public#11]
to_world is not used in parse_ply function:
https://github.com/BachiLi/lajolla_public/blame/b8ca4d02e2c7629db672d50a113c9dd04c54c906/src/parsers/parse_ply.cpp#L9

**Comment by BachiLi** [comment]
Oops, it does look like a bug. Good catch!

**Comment by BachiLi** [comment]
Fixed in https://github.com/BachiLi/lajolla_public/commit/8845202da8e64ed6d253cf8a0a91f1560ad6d94a

**Comment by BachiLi** [comment]
Actually https://github.com/BachiLi/lajolla_public/commit/1b77cea80ccf95f0ca4bf35518b36c309895e714 is the right fix.
