### ISSUE TITLE
Error in guassian.inl after changing Real from double to float

### ISSUE THREAD

**Issue by TaKeTube** [BachiLi/lajolla_public#12]
If we change `Real` from `double` to `float`, we will get the following error:
![image](https://github.com/BachiLi/lajolla_public/assets/51813149/98ffe3f5-b980-46c2-9a15-e813de2b114f)
Changing 1e-8 to Real(1e-8) will solve this problem.

**Comment by BachiLi** [comment]
Thanks! Fixed in https://github.com/BachiLi/lajolla_public/commit/b4e0a7ecbffc756a602fe4f9e01183eb381aeafe
